const allMe = document.querySelector('.all')
const breakFast = document.querySelector('.breakfast')
const lunchShow = document.querySelector('.lunch')
const shaKes = document.querySelector('.shakes')
const dinnEr = document.querySelector('.dinner')
